// <auto-generated />
using System;
using ExpenseTracker.Services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTracker.Services.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240304092101_tblroles")]
    partial class tblroles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblBankFileGenDetails", b =>
                {
                    b.Property<string>("BankFileBatchId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BankFileExt")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BankFileGenBy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("BankFileGenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BankFilePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("BankFileBatchId");

                    b.ToTable("BankFileGenDetails");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblBankMaster", b =>
                {
                    b.Property<string>("BankCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BankAccNo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("BankAccountType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BankAdd01")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BankAdd02")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BankAdd03")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BankAdd04")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BankAdd05")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BankBranchCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BankClientCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BankEmailId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankGlCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BankIfscCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EntryBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("SeriesDetails")
                        .HasMaxLength(30)
                        .HasColumnType("bigint");

                    b.HasKey("BankCode");

                    b.ToTable("BankMasters");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblMenu", b =>
                {
                    b.Property<int>("MENU_ID")
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime?>("DELETE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DELETE_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ENTRY_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ENTRY_ID")
                        .HasColumnType("int");

                    b.Property<string>("MENU_DESC")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("MENU_LEVEL")
                        .HasColumnType("int");

                    b.Property<string>("MENU_URL")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime?>("MODIFY_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MODIFY_ID")
                        .HasColumnType("int");

                    b.Property<int?>("ORDER_LEVEL")
                        .HasColumnType("int");

                    b.Property<int?>("PARENT_MENU")
                        .HasColumnType("int");

                    b.Property<bool?>("STATUS")
                        .HasColumnType("bit");

                    b.HasKey("MENU_ID");

                    b.HasIndex("MENU_ID")
                        .IsUnique();

                    b.ToTable("TBL_MENU", "dbo");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblMenuAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("MENU_ACCESS_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DELETE_DATE");

                    b.Property<int?>("DeleteId")
                        .HasColumnType("int")
                        .HasColumnName("DELETE_ID");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("ENTRY_DATE");

                    b.Property<int?>("EntryId")
                        .HasColumnType("INT")
                        .HasColumnName("ENTRY_ID");

                    b.Property<int>("MenuId")
                        .HasColumnType("INT")
                        .HasColumnName("MENU_ID");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("MODIFY_DATE");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("INT")
                        .HasColumnName("MODIFY_ID");

                    b.Property<int>("RoleId")
                        .HasColumnType("INT")
                        .HasColumnName("ROLE_ID");

                    b.Property<bool?>("Status")
                        .HasColumnType("BIT")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("MenuId")
                        .IsUnique();

                    b.ToTable("TBL_MENU_ACCESS", "dbo");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblPaymentDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllocRef")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BankFileBatchId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BatchNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BeneAccNo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BeneAdd01")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BeneAdd02")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BeneAdd03")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BeneAdd04")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BeneAdd05")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BeneBankName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BeneBranchCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BeneEmailId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BeneIfscCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BeneMobileNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BeneName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BenePhoneNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BeneState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BeneSurName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContryCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CurrencyType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("EntryBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FmsSource")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid>("GUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("JrnalLine")
                        .HasColumnType("int");

                    b.Property<string>("JrnalNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LocationDetails")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("PmtDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PmtRejectionReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PmtRemarks")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PmtRespFileId")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PmtStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PmtUnqRefNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PmtUtrDetails")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("ReversePostingStatus")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tdescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Tds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Treference")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Udf1")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Udf2")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Udf3")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Udf4")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Udf5")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("UnqRefNo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("ValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidationRefNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("BankCode");

                    b.HasIndex("BankFileBatchId");

                    b.ToTable("PaymentDetails");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ROLE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<int?>("BuId")
                        .HasColumnType("int")
                        .HasColumnName("BU_ID");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETE_DATE");

                    b.Property<int?>("DeleteId")
                        .HasColumnType("int")
                        .HasColumnName("DELETE_ID");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ENTRY_DATE");

                    b.Property<int?>("EntryId")
                        .HasColumnType("int")
                        .HasColumnName("ENTRY_ID");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime")
                        .HasColumnName("MODIFY_DATE");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int")
                        .HasColumnName("MODIFY_ID");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("varchar(MAX)")
                        .HasColumnName("ROLE_DESCRIPTION");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ROLE_NAME");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.HasKey("RoleId");

                    b.ToTable("TBL_ROLE", "dbo");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblUser", b =>
                {
                    b.Property<int>("InternalUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("INTERNAL_USER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InternalUserId"));

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACCOUNT_NAME");

                    b.Property<string>("AccountNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACCOUNT_NO");

                    b.Property<decimal?>("ApprovalLimit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("APPROVAL_LIMIT");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BANK_NAME");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BRANCH");

                    b.Property<string>("BuAccess")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BU_ACCESS");

                    b.Property<string>("BuName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BU_NAME");

                    b.Property<string>("BuSunCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BU_SUN_CODE");

                    b.Property<int?>("BusinessUnit")
                        .HasColumnType("int")
                        .HasColumnName("BUSINESS_UNIT");

                    b.Property<int?>("DashboardId")
                        .HasColumnType("int")
                        .HasColumnName("DASHBOARD_ID");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<int?>("DeleteId")
                        .HasColumnType("int")
                        .HasColumnName("DELETE_ID");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DEPARTMENT_ID");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DEPARTMENT_NAME");

                    b.Property<int?>("DesignationId")
                        .HasColumnType("int")
                        .HasColumnName("DESIGNATION_ID");

                    b.Property<string>("DesignationName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESIGNATION_NAME");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("int")
                        .HasColumnName("DIVISION_ID");

                    b.Property<string>("DivisionName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DIVISION_NAME");

                    b.Property<string>("EmpPeopleSoftCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMP_PEOPLESOFT_CODE");

                    b.Property<string>("EmpSunCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMP_SUN_CODE");

                    b.Property<string>("EmployeeCategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMPLOYEE_CATEGORY");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("EMPLOYEE_CODE");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("ENTITY_ID");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ENTITY_NAME");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ENTRY_DATE");

                    b.Property<int?>("EntryId")
                        .HasColumnType("int")
                        .HasColumnName("ENTRY_ID");

                    b.Property<string>("IfscCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IFSC_CODE");

                    b.Property<bool?>("IsAd")
                        .HasColumnType("bit")
                        .HasColumnName("IS_AD");

                    b.Property<bool?>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("IS_LOCKED");

                    b.Property<bool?>("IsSharedAdminStaff")
                        .HasColumnType("bit")
                        .HasColumnName("IS_SHARED_ADMIN_STAFF");

                    b.Property<bool?>("IsSharedServiceStaff")
                        .HasColumnType("bit")
                        .HasColumnName("IS_SHARED_SERVICE_STAFF");

                    b.Property<string>("ItemAccess")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ITEM_ACCESS");

                    b.Property<string>("JobCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JOB_CODE");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("JOIN_DATE");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LOCATION_ID");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LOCATION_NAME");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("MANAGER_ID");

                    b.Property<string>("ManagerName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MANAGER_NAME");

                    b.Property<int?>("MangerId")
                        .HasColumnType("int")
                        .HasColumnName("MANGER_ID");

                    b.Property<decimal?>("MaxAdvOutLimit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MAX_ADV_OUT_LIMIT");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOBILE_NO");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFY_DATE");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int")
                        .HasColumnName("MODIFY_ID");

                    b.Property<int?>("NoOfAttempt")
                        .HasColumnType("int")
                        .HasColumnName("NO_OF_ATTEMPT");

                    b.Property<string>("PanNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PAN_NO");

                    b.Property<DateTime?>("PasswordModifyDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PASSWORD_MODIFY_DATE");

                    b.Property<string>("PrevPassword")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PREV_PASSWORD");

                    b.Property<string>("ReimbursementAccess")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("REIMBURSEMENT_ACCESS");

                    b.Property<string>("RoleAccess")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ROLE_ACCESS");

                    b.Property<string>("RoleAccessName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ROLE_ACCESS_NAME");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<string>("T1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("T1");

                    b.Property<string>("T2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("T2");

                    b.Property<string>("UserAccess")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USER_ACCESS");

                    b.Property<string>("UserEmailId")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("USER_EMAIL_ID");

                    b.Property<string>("UserEntryCategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USER_ENTRY_CATEGORY");

                    b.Property<string>("UserLoginCode")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("USER_LOGIN_CODE");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USER_NAME");

                    b.Property<string>("UserPassword")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("USER_PASSWORD");

                    b.HasKey("InternalUserId");

                    b.HasIndex("InternalUserId")
                        .IsUnique();

                    b.ToTable("TBL_USER", "dbo");
                });

            modelBuilder.Entity("TblBusinessUnit", b =>
                {
                    b.Property<int>("BusinessUnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BUSINESS_UNIT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessUnitID"));

                    b.Property<string>("BUAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BU_ADDRESS");

                    b.Property<string>("BUCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BU_CODE");

                    b.Property<string>("BUName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BU_NAME");

                    b.Property<string>("BusinessUnitCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BUSINESS_UNIT_CODE");

                    b.Property<string>("CINNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CIN_NO");

                    b.Property<string>("CountryID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COUNTRY_ID");

                    b.Property<string>("DOSTemplate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOS_TEMPLATE");

                    b.Property<decimal?>("DeductionCapAmt")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("DEDUCTION_CAP_AMT");

                    b.Property<decimal?>("DeductionCapPer")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("DEDUCTION_CAP_PER");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<int?>("DeleteID")
                        .HasColumnType("int")
                        .HasColumnName("DELETE_ID");

                    b.Property<string>("DepartmentAccess")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DEPARTMENT_ACCESS");

                    b.Property<string>("DivisionAccess")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DIVISION_ACCESS");

                    b.Property<int?>("DivisionID")
                        .HasColumnType("int")
                        .HasColumnName("DIVISION_ID");

                    b.Property<string>("DivisionName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DIVISION_NAME");

                    b.Property<int?>("EntityID")
                        .HasColumnType("int")
                        .HasColumnName("ENTITY_ID");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ENITY_NAME");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ENTRY_DATE");

                    b.Property<int?>("EntryID")
                        .HasColumnType("int")
                        .HasColumnName("ENTRY_ID");

                    b.Property<string>("GSTIN")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GSTIN");

                    b.Property<int?>("HisLocationCode")
                        .HasColumnType("int")
                        .HasColumnName("HIS_LOCATION_CODE");

                    b.Property<string>("IACode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IACODE");

                    b.Property<string>("LocationAccess")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LOCATION_ACCESS");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFY_DATE");

                    b.Property<int?>("ModifyID")
                        .HasColumnType("int")
                        .HasColumnName("MODIFY_ID");

                    b.Property<string>("NEFTDetails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NEFT_DETAILS");

                    b.Property<string>("PANNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PAN_NO");

                    b.Property<string>("STNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NO");

                    b.Property<string>("StateCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STATE_CODE");

                    b.Property<string>("StateNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STATE_NUMBER");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.Property<string>("SunAccountingLocationT1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUN_ACCOUNTING_LOCATION_T1");

                    b.Property<string>("SunCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUN_CODE");

                    b.Property<string>("SunEmpCashCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUN_EMP_CASH_CODE");

                    b.Property<string>("SunInterUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUN_INTER_UNIT");

                    b.Property<string>("SunIntercompany")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUN_INTERCOMPANY");

                    b.Property<string>("SunWorkLocationT2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUN_WORK_LOCATION_T2");

                    b.Property<string>("TINNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIN_NO");

                    b.Property<string>("UploadPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UPLOAD_PATH");

                    b.HasKey("BusinessUnitID");

                    b.ToTable("TBL_BUSINESS_UNIT", "dbo");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblPaymentDetails", b =>
                {
                    b.HasOne("ExpenseTracker.Services.Models.EntityModels.TblBankMaster", "BankMaster")
                        .WithMany()
                        .HasForeignKey("BankCode");

                    b.HasOne("ExpenseTracker.Services.Models.EntityModels.TblBankFileGenDetails", "BankFileGenDetails")
                        .WithMany()
                        .HasForeignKey("BankFileBatchId");

                    b.Navigation("BankFileGenDetails");

                    b.Navigation("BankMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
