// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ExpenseTracker.Services.Data;

#nullable disable

namespace ExpenseTracker.Services.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240713142744_subplanmasterchanges")]
    partial class subplanmasterchanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.BusinessDevTeam", b =>
                {
                    b.Property<int>("BDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BDID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BDId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("ENTRY_DATE");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("date")
                        .HasColumnName("JOINING_DATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NAME");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.HasKey("BDId");

                    b.ToTable("TBL_BUSINESS_DEV_TEAM");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.ClientMaster", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CLIENT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"), 10000L);

                    b.Property<string>("AadharAttachmentPath")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("AADHAR_ATTACHMENT_PATH");

                    b.Property<string>("AadharNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("AADHAR_NO");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FamilyTag")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FAMILY_TAG");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("MailAddressLine1")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("MAIL_ADDRESS_LINE1");

                    b.Property<string>("MailAddressLine2")
                        .HasColumnType("varchar(60)")
                        .HasColumnName("MAIL_ADDRESS_LINE2");

                    b.Property<string>("MailAddressLine3")
                        .HasColumnType("varchar(60)")
                        .HasColumnName("MAIL_ADDRESS_LINE3");

                    b.Property<string>("MailCity")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MAIL_CITY");

                    b.Property<int>("MailPinCode")
                        .HasColumnType("int")
                        .HasColumnName("MAIL_PIN_CODE");

                    b.Property<string>("MailState")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MAIL_STATE");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MOBILE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NOTES");

                    b.Property<string>("OfficeAddressLine1")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("OFFICE_ADDRESS_LINE1");

                    b.Property<string>("OfficeAddressLine2")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("OFFICE_ADDRESS_LINE2");

                    b.Property<string>("OfficeAddressLine3")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("OFFICE_ADDRESS_LINE3");

                    b.Property<string>("OfficeCity")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("OFFICE_CITY");

                    b.Property<string>("OfficePinCode")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("OFFICE_PIN_CODE");

                    b.Property<string>("OfficeState")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("OFFICE_STATE");

                    b.Property<string>("PanAttachmentPath")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PAN_ATTACHMENT_PATH");

                    b.Property<string>("PanNo")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("PAN_NO");

                    b.Property<string>("PerAddressLine1")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("PER_ADDRESS_LINE1");

                    b.Property<string>("PerAddressLine2")
                        .HasColumnType("varchar(60)")
                        .HasColumnName("PER_ADDRESS_LINE2");

                    b.Property<string>("PerAddressLine3")
                        .HasColumnType("varchar(60)")
                        .HasColumnName("PER_ADDRESS_LINE3");

                    b.Property<string>("PerCity")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PER_CITY");

                    b.Property<int>("PerPinCode")
                        .HasColumnType("int")
                        .HasColumnName("PER_PIN_CODE");

                    b.Property<string>("PerState")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PER_STATE");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("PHONE");

                    b.Property<string>("ProfileImageAttachmentPath")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PROFILE_IMAGE_ATTACHMENT_PATH");

                    b.Property<string>("ReferredBy")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("REFERRED_BY");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.HasKey("ClientId");

                    b.ToTable("CLIENT_MASTER");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.PlanMaster", b =>
                {
                    b.Property<string>("PlanCode")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("PLAN_CODE");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PLAN_NAME");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.HasKey("PlanCode");

                    b.ToTable("PLAN_MASTER");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.SubPlansMaster", b =>
                {
                    b.Property<int>("SubPlansId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SUB_PLANS_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubPlansId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("INTEREST_RATE");

                    b.Property<decimal>("MinInvestment")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MIN_INVESTMENT");

                    b.Property<int>("PayoutFrequencyInMonths")
                        .HasColumnType("int")
                        .HasColumnName("PAYOUT_FREQUENCY_IN_MONTHS");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("PLAN_CODE");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.HasKey("SubPlansId");

                    b.ToTable("SUB_PLANS_MASTER");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblApplicationParameter", b =>
                {
                    b.Property<int>("ParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PARAMETER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParameterId"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<int?>("DeleteId")
                        .HasColumnType("int")
                        .HasColumnName("DELETE_ID");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ENTRY_DATE");

                    b.Property<int?>("EntryId")
                        .HasColumnType("int")
                        .HasColumnName("ENTRY_ID");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFY_DATE");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int")
                        .HasColumnName("MODIFY_ID");

                    b.Property<string>("Parameter")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("PARAMETER");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<string>("Value")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("VALUE");

                    b.HasKey("ParameterId");

                    b.ToTable("TBL_APPLICATION_PARAMETER", "dbo");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblAuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ACTION_DATE")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ActionDescription")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ACTION_DESC");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COMMENTS");

                    b.Property<string>("ProcessDescription")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PROCESS_DESC");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("PROCESS_ID");

                    b.Property<int?>("UniqueId")
                        .HasColumnType("int")
                        .HasColumnName("UNQ_ID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("Id");

                    b.ToTable("TBL_AUDIT_TRAIL");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblBankMaster", b =>
                {
                    b.Property<string>("BankCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BankAccNo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("BankAccountType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BankAdd01")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BankAdd02")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BankAdd03")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BankAdd04")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BankAdd05")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BankBranchCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BankClientCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BankEmailId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankGlCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BankIfscCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EntryBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SeriesDetails")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("BankCode");

                    b.ToTable("BankMasters");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblBorrowLetterDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChequeDate")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CHEQUE_DATE");

                    b.Property<string>("ChequeNo")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CHEQUE_NO");

                    b.Property<string>("SentDate")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SENT_DATE");

                    b.Property<Guid>("SubscriptionGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SUBSCRIPTION_GUID");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("SUBSCRIPTION_ID");

                    b.Property<string>("TrackingNo")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TRACKING_NO");

                    b.HasKey("Id");

                    b.ToTable("TBL_BORROW_LETTER_DETAILS");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblCustomReportMaster", b =>
                {
                    b.Property<int>("CustomReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CUSTOM_REPORT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomReportId"));

                    b.Property<string>("ColumnFilter")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("COLUMN_FILTER");

                    b.Property<string>("CustomReportCode")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("CUSTOM_REPORT_CODE");

                    b.Property<string>("CustomReportDesc")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("CUSTOM_REPORT_DESC");

                    b.Property<string>("CustomReportName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("CUSTOM_REPORT_NAME");

                    b.Property<string>("CustomReportQuery")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("CUSTOM_REPORT_QUERY");

                    b.Property<string>("DagDesc")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DAG_DESC");

                    b.Property<string>("DateFilter")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DATE_FILTER");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETE_DATE");

                    b.Property<int?>("DeleteId")
                        .HasColumnType("int")
                        .HasColumnName("DELETE_ID");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ENTRY_DATE");

                    b.Property<int?>("EntryId")
                        .HasColumnType("int")
                        .HasColumnName("ENTRY_ID");

                    b.Property<int?>("IsDag")
                        .HasColumnType("int")
                        .HasColumnName("ISDAG");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime")
                        .HasColumnName("MODIFY_DATE");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int")
                        .HasColumnName("MODIFY_ID");

                    b.Property<string>("OrderFilter")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ORDER_FILTER");

                    b.Property<string>("RoleAccess")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ROLE_ACCESS");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.HasKey("CustomReportId");

                    b.ToTable("TBL_CUSTOM_REPORT_MASTER", "dbo");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblDepartment", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DEPARTMENT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<int?>("DeleteId")
                        .HasColumnType("int")
                        .HasColumnName("DELETE_ID");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DEPARTMENT_CODE");

                    b.Property<string>("DepartmentDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DEPARTMENT_DESCRIPTION");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ENTRY_DATE");

                    b.Property<int?>("EntryId")
                        .HasColumnType("int")
                        .HasColumnName("ENTRY_ID");

                    b.Property<bool?>("IDepOnly")
                        .HasColumnType("bit")
                        .HasColumnName("L_DEP_ONLY");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFY_DATE");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int")
                        .HasColumnName("MODIFY_ID");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.Property<string>("SunAccountCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUN_ACCOUNT_CODE");

                    b.HasKey("DepartmentId");

                    b.ToTable("TBL_DEPARTMENT", "dbo");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("LOCATION_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Address1")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("ADDRESS1");

                    b.Property<string>("Address2")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("ADDRESS2");

                    b.Property<string>("Address3")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("ADDRESS3");

                    b.Property<string>("Address4")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("ADDRESS4");

                    b.Property<string>("Address5")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("ADDRESS5");

                    b.Property<int?>("BusinessUnit")
                        .HasColumnType("int")
                        .HasColumnName("BUSINESS_UNIT");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CITY");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<int?>("DeleteId")
                        .HasColumnType("int")
                        .HasColumnName("DELETE_ID");

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMAIL_ID");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ENTRY_DATE");

                    b.Property<int?>("EntryId")
                        .HasColumnType("int")
                        .HasColumnName("ENTRY_ID");

                    b.Property<string>("LocationCode")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("LOCATION_CODE");

                    b.Property<string>("LocationName")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("LOCATION_NAME");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFY_DATE");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int")
                        .HasColumnName("MODIFY_ID");

                    b.Property<string>("Pincode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PINCODE");

                    b.Property<string>("PrintAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PRINT_ADDRESS");

                    b.Property<int?>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("STATE_ID");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TELEPHONE");

                    b.HasKey("LocationId");

                    b.ToTable("TBL_LOC", "dbo");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblMenu", b =>
                {
                    b.Property<int>("MENU_ID")
                        .HasColumnType("int")
                        .HasColumnName("MENU_ID");

                    b.Property<string>("Action")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("Action");

                    b.Property<string>("Controller")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("Controller");

                    b.Property<DateTime?>("DELETE_DATE")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<int?>("DELETE_ID")
                        .HasColumnType("int")
                        .HasColumnName("DELETE_ID");

                    b.Property<DateTime?>("ENTRY_DATE")
                        .HasColumnType("datetime2")
                        .HasColumnName("ENTRY_DATE");

                    b.Property<int?>("ENTRY_ID")
                        .HasColumnType("int")
                        .HasColumnName("ENTRY_ID");

                    b.Property<string>("MENU_DESC")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("MENU_DESC");

                    b.Property<int?>("MENU_LEVEL")
                        .HasColumnType("int")
                        .HasColumnName("MENU_LEVEL");

                    b.Property<string>("MENU_URL")
                        .HasColumnType("VARCHAR(5000)")
                        .HasColumnName("MENU_URL");

                    b.Property<DateTime?>("MODIFY_DATE")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFY_DATE");

                    b.Property<int?>("MODIFY_ID")
                        .HasColumnType("int")
                        .HasColumnName("MODIFY_ID");

                    b.Property<int?>("ORDER_LEVEL")
                        .HasColumnType("int")
                        .HasColumnName("ORDER_LEVEL");

                    b.Property<int?>("PARENT_MENU")
                        .HasColumnType("int")
                        .HasColumnName("PARENT_MENU");

                    b.Property<bool?>("STATUS")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.HasKey("MENU_ID");

                    b.HasIndex("MENU_ID")
                        .IsUnique();

                    b.ToTable("TBL_MENU", "dbo");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblMenuAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("MENU_ACCESS_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DELETE_DATE");

                    b.Property<int?>("DeleteId")
                        .HasColumnType("int")
                        .HasColumnName("DELETE_ID");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("ENTRY_DATE");

                    b.Property<int?>("EntryId")
                        .HasColumnType("INT")
                        .HasColumnName("ENTRY_ID");

                    b.Property<int>("MenuId")
                        .HasColumnType("INT")
                        .HasColumnName("MENU_ID");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("MODIFY_DATE");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("INT")
                        .HasColumnName("MODIFY_ID");

                    b.Property<int>("RoleId")
                        .HasColumnType("INT")
                        .HasColumnName("ROLE_ID");

                    b.Property<bool?>("Status")
                        .HasColumnType("BIT")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("MenuId")
                        .IsUnique();

                    b.ToTable("TBL_MENU_ACCESS", "dbo");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblPaymentDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllocRef")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BankFileBatchId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BatchNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BeneAccNo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BeneAdd01")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BeneAdd02")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BeneAdd03")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BeneAdd04")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BeneAdd05")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BeneBankName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BeneBranchCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BeneEmailId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BeneIfscCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BeneMobileNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BeneName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BenePhoneNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BeneState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BeneSurName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContryCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CurrencyType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("EntryBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FmsSource")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid>("GUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("JrnalLine")
                        .HasColumnType("int");

                    b.Property<string>("JrnalNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LocationDetails")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("PmtDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PmtRejectionReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PmtRemarks")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PmtRespFileId")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PmtStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PmtUnqRefNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PmtUtrDetails")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("ReversePostingStatus")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tdescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Tds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Treference")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Udf1")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Udf2")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Udf3")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Udf4")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Udf5")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("UnqRefNo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("ValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidationRefNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("TblPaymentDetails");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblPaymentSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SCHEDULE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AMOUNT_PAID");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Day")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DAY");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime")
                        .HasColumnName("DUE_DATE");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("INTEREST_RATE");

                    b.Property<decimal?>("InvestedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("INVESTED_AMOUNT");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NOTES");

                    b.Property<string>("PaidBy")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PAID_BY");

                    b.Property<decimal?>("PayableAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PAYABLE_AMOUNT");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("PAYMENT_DATE");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("PAYMENT_MODE");

                    b.Property<string>("PaymentProofAttachment")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PAYMENT_PROOF_ATTACHMENT");

                    b.Property<string>("PaymentUtr")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("PAYMENT_UTR");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ClientId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("PAYMENT_SCHEDULE");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ROLE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<int?>("BuId")
                        .HasColumnType("int")
                        .HasColumnName("BU_ID");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETE_DATE");

                    b.Property<int?>("DeleteId")
                        .HasColumnType("int")
                        .HasColumnName("DELETE_ID");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ENTRY_DATE");

                    b.Property<int?>("EntryId")
                        .HasColumnType("int")
                        .HasColumnName("ENTRY_ID");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime")
                        .HasColumnName("MODIFY_DATE");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int")
                        .HasColumnName("MODIFY_ID");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("varchar(MAX)")
                        .HasColumnName("ROLE_DESCRIPTION");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ROLE_NAME");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.HasKey("RoleId");

                    b.ToTable("TBL_ROLE", "dbo");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int?>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("FORM_ID");

                    b.Property<int?>("NextStatus")
                        .HasColumnType("int")
                        .HasColumnName("NEXT_STATUS");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("int")
                        .HasColumnName("PREVIOUS_STATUS");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("PROCESS_ID");

                    b.Property<int?>("StatusValue")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("TBL_STATUS");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblSubscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SUBSCRIPTION_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("APPROVED_BY");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("APPROVED_DATE");

                    b.Property<int>("BorrowLetterStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("BORROW_LETTER_STATUS");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("CLIENT_ID");

                    b.Property<int>("ClientMasterClientId")
                        .HasColumnType("int")
                        .HasColumnName("ClientMasterClientId");

                    b.Property<string>("ClosedBy")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CLOSED_BY");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CLOSING_DATE");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateOfInvestment")
                        .HasColumnType("datetime")
                        .HasColumnName("DATE_OF_INVESTMENT");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("InvestmentAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("INVESTMENT_AMOUNT");

                    b.Property<DateTime?>("InvestmentReceivedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("INVESTMENT_RCVD_DATE");

                    b.Property<string>("InvestmentReceivedDetails")
                        .HasColumnType("varchar(300)")
                        .HasColumnName("INVESTMENT_RECVD_DETAILS");

                    b.Property<bool>("IsPaymentScheduleAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("IS_PAYMENT_SCEDULE_AVAILABLE");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("datetime")
                        .HasColumnName("MATURITY_DATE");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NOTES");

                    b.Property<int?>("OldSubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("OLD_SUBSCRIPTION_ID");

                    b.Property<string>("PayoutBankAccountHolderName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PAYOUT_BANK_ACCOUNT_HOLDER_NAME");

                    b.Property<string>("PayoutBankAccountNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PAYOUT_BANK_ACCOUNT_NO");

                    b.Property<string>("PayoutBankIfscCode")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PAYOUT_BANK_IFSC_CODE");

                    b.Property<string>("PayoutBankName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PAYOUT_BANK_NAME");

                    b.Property<int>("PayoutFrequency")
                        .HasColumnType("int")
                        .HasColumnName("PAYOUT_FREQUENCY");

                    b.Property<decimal>("PayoutFrequencyInterestRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PAYOUT_FREQUENCY_INTEREST_RATE");

                    b.Property<string>("PayoutMethod")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PAYOUT_METHOD");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("PLAN_CODE");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PLAN_NAME");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("SUBSCRIPTION_TYPE");

                    b.Property<int>("Tenure")
                        .HasColumnType("int")
                        .HasColumnName("TENURE");

                    b.Property<decimal>("TotalInterest")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TOTAL_INTEREST");

                    b.Property<string>("UpiId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPI_ID");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientMasterClientId");

                    b.HasIndex("PlanCode");

                    b.ToTable("SUBSCRIPTION");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblUser", b =>
                {
                    b.Property<int>("InternalUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("INTERNAL_USER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InternalUserId"));

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACCOUNT_NAME");

                    b.Property<string>("AccountNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACCOUNT_NO");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BANK_NAME");

                    b.Property<string>("BuAccess")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BU_ACCESS");

                    b.Property<string>("BuName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BU_NAME");

                    b.Property<int?>("BusinessUnit")
                        .HasColumnType("int")
                        .HasColumnName("BUSINESS_UNIT");

                    b.Property<int?>("DashboardId")
                        .HasColumnType("int")
                        .HasColumnName("DASHBOARD_ID");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<int?>("DeleteId")
                        .HasColumnType("int")
                        .HasColumnName("DELETE_ID");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DEPARTMENT_ID");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DEPARTMENT_NAME");

                    b.Property<string>("DivisionName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DIVISION_NAME");

                    b.Property<string>("EmployeeCategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMPLOYEE_CATEGORY");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("EMPLOYEE_CODE");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ENTRY_DATE");

                    b.Property<int?>("EntryId")
                        .HasColumnType("int")
                        .HasColumnName("ENTRY_ID");

                    b.Property<string>("IfscCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IFSC_CODE");

                    b.Property<bool?>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("IS_LOCKED");

                    b.Property<string>("ItemAccess")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ITEM_ACCESS");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("JOIN_DATE");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LOCATION_ID");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("MANAGER_ID");

                    b.Property<string>("ManagerName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MANAGER_NAME");

                    b.Property<int?>("MangerId")
                        .HasColumnType("int")
                        .HasColumnName("MANGER_ID");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOBILE_NO");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFY_DATE");

                    b.Property<int?>("ModifyId")
                        .HasColumnType("int")
                        .HasColumnName("MODIFY_ID");

                    b.Property<int?>("NoOfAttempt")
                        .HasColumnType("int")
                        .HasColumnName("NO_OF_ATTEMPT");

                    b.Property<string>("PanNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PAN_NO");

                    b.Property<DateTime?>("PasswordModifyDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PASSWORD_MODIFY_DATE");

                    b.Property<string>("PrevPassword")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PREV_PASSWORD");

                    b.Property<string>("RoleAccess")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ROLE_ACCESS");

                    b.Property<string>("RoleAccessName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ROLE_ACCESS_NAME");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<string>("UserAccess")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USER_ACCESS");

                    b.Property<string>("UserEmailId")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("USER_EMAIL_ID");

                    b.Property<string>("UserEntryCategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USER_ENTRY_CATEGORY");

                    b.Property<string>("UserLoginCode")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("USER_LOGIN_CODE");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USER_NAME");

                    b.Property<string>("UserPassword")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("USER_PASSWORD");

                    b.HasKey("InternalUserId");

                    b.HasIndex("InternalUserId")
                        .IsUnique();

                    b.ToTable("TBL_USER", "dbo");
                });

            modelBuilder.Entity("TblBusinessUnit", b =>
                {
                    b.Property<int>("BusinessUnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BUSINESS_UNIT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessUnitID"));

                    b.Property<string>("BUAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BU_ADDRESS");

                    b.Property<string>("BUCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BU_CODE");

                    b.Property<string>("BUName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BU_NAME");

                    b.Property<string>("BusinessUnitCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BUSINESS_UNIT_CODE");

                    b.Property<string>("CINNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CIN_NO");

                    b.Property<string>("CountryID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COUNTRY_ID");

                    b.Property<string>("DOSTemplate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOS_TEMPLATE");

                    b.Property<decimal?>("DeductionCapAmt")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("DEDUCTION_CAP_AMT");

                    b.Property<decimal?>("DeductionCapPer")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("DEDUCTION_CAP_PER");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<int?>("DeleteID")
                        .HasColumnType("int")
                        .HasColumnName("DELETE_ID");

                    b.Property<string>("DepartmentAccess")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DEPARTMENT_ACCESS");

                    b.Property<string>("DivisionAccess")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DIVISION_ACCESS");

                    b.Property<int?>("DivisionID")
                        .HasColumnType("int")
                        .HasColumnName("DIVISION_ID");

                    b.Property<string>("DivisionName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DIVISION_NAME");

                    b.Property<int?>("EntityID")
                        .HasColumnType("int")
                        .HasColumnName("ENTITY_ID");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ENITY_NAME");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ENTRY_DATE");

                    b.Property<int?>("EntryID")
                        .HasColumnType("int")
                        .HasColumnName("ENTRY_ID");

                    b.Property<string>("GSTIN")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GSTIN");

                    b.Property<int?>("HisLocationCode")
                        .HasColumnType("int")
                        .HasColumnName("HIS_LOCATION_CODE");

                    b.Property<string>("IACode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IACODE");

                    b.Property<string>("LocationAccess")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LOCATION_ACCESS");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFY_DATE");

                    b.Property<int?>("ModifyID")
                        .HasColumnType("int")
                        .HasColumnName("MODIFY_ID");

                    b.Property<string>("NEFTDetails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NEFT_DETAILS");

                    b.Property<string>("PANNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PAN_NO");

                    b.Property<string>("STNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NO");

                    b.Property<string>("StateCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STATE_CODE");

                    b.Property<string>("StateNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STATE_NUMBER");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.Property<string>("SunAccountingLocationT1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUN_ACCOUNTING_LOCATION_T1");

                    b.Property<string>("SunCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUN_CODE");

                    b.Property<string>("SunEmpCashCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUN_EMP_CASH_CODE");

                    b.Property<string>("SunInterUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUN_INTER_UNIT");

                    b.Property<string>("SunIntercompany")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUN_INTERCOMPANY");

                    b.Property<string>("SunWorkLocationT2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUN_WORK_LOCATION_T2");

                    b.Property<string>("TINNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIN_NO");

                    b.Property<string>("UploadPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UPLOAD_PATH");

                    b.HasKey("BusinessUnitID");

                    b.ToTable("TBL_BUSINESS_UNIT", "dbo");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblPaymentSchedule", b =>
                {
                    b.HasOne("ExpenseTracker.Services.Models.EntityModels.ClientMaster", "ClientMaster")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Services.Models.EntityModels.TblSubscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientMaster");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.TblSubscription", b =>
                {
                    b.HasOne("ExpenseTracker.Services.Models.EntityModels.ClientMaster", "ClientMaster")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Services.Models.EntityModels.ClientMaster", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("ClientMasterClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Services.Models.EntityModels.PlanMaster", "PlanMaster")
                        .WithMany()
                        .HasForeignKey("PlanCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientMaster");

                    b.Navigation("PlanMaster");
                });

            modelBuilder.Entity("ExpenseTracker.Services.Models.EntityModels.ClientMaster", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
